name: keyri_example
version: 1.7.0
description: Demonstrates how to use the Keyri plugin.
publish_to: 'none'

environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  keyri_v3:
    path: ../
  cupertino_icons: ^1.0.6
  mobile_scanner: 4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
