name: keyri_v3
description: Keyri QR Login plugin for Flutter. Provides Keyri SDK capabilities for secure and passwordless login.
version: 1.7.1
homepage: https://keyri.com

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=2.8.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.keyrico.keyri
        pluginClass: KeyriPlugin
      ios:
        pluginClass: KeyriPlugin
