name: keyri_v3
description: Keyri QR Login plugin for Flutter. Provides Keyri SDK capabilities for secure and passwordless login.
version: 1.4.3
homepage: https://keyri.com

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  mobile_scanner: ^3.4.1

flutter:
  plugin:
    platforms:
      android:
        package: com.keyrico.keyri
        pluginClass: KeyriPlugin
      ios:
        pluginClass: KeyriPlugin
